#!/bin/bash
#SBATCH --job-name="weights_s29"
#SBATCH --account=burke
#SBATCH --partition=nes2.8,brd2.4
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --time=12:00:00
#SBATCH --mem=8G

ml purge
ml miniconda/3/own
srun python seed_analysis.py s29
