#!/bin/bash
#SBATCH --job-name="strong_corr_large"
#SBATCH --account=burke
#SBATCH --partition=nes2.8,brd2.4
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --time=12:00:00
#SBATCH --mem=48G

ml purge
ml gnu/9.1.0
ml miniconda/3/own
srun python train.py > output.txt
