#!/bin/bash
#SBATCH --job-name="t2_v0_s20"
#SBATCH --account=burke
#SBATCH --partition=nes2.8,brd2.4
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --time=12:00:00
#SBATCH --mem=8G

ml purge
ml gnu/9.1.0
ml miniconda/3/own
srun python /DFS-B/DATA/burke/pedersor/jax_dft_dev/models/ions/ksr_lsda/lsda/paper_fig/train_validate.py t2 v0 s20 > output.txt 
